# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: 泽民博客
email: 465474307@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  夏泽民的个人主页，学习笔记。
baseurl: "/MyBlog" # the subpath of your site, e.g. /blog
url: "https://xiazemin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xiazemin
github_username:  xiazemin

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 2
paginate_path: "page:num"

comments: true
excerpt_separator: <!-- more -->
